import type { Prisma } from '@/generated/prisma/client'

/**
 * A temporary shortening of the menu to the dishes Javatri has its own photograph of.
 *
 * The owner's 79 photographs come out of the client's PDF into public/dishes/pdf — product shots,
 * cut out on white, carrying the wordmark. The other 117 dishes fall back to Wikimedia library
 * photographs of the *dish type*, which the menu labels as serving suggestions. This switch hides
 * those 117 until the owner says otherwise.
 *
 * Nothing is deleted, and nothing in the database is changed. The dishes, their prices, their
 * allergens and their sort order are all exactly where they were; this is a `where` clause on the
 * way out. Set HIDE_DISHES_WITHOUT_OWN_PHOTO to false and all 196 are back in their original
 * places on the next request — no migration, no re-seed, no restore step.
 *
 * menu-hidden.json at the repo root lists precisely what this is hiding, regenerated by
 * `npm run menu:hidden`.
 */
export const HIDE_DISHES_WITHOUT_OWN_PHOTO = true

/** Where the extractor writes the owner's own photographs. */
export const OWN_PHOTO_PREFIX = '/dishes/pdf/'

/**
 * The filter, in one place.
 *
 * Applied to every menu read including the pricing catalogue — a dish hidden from the menu but
 * still priceable at checkout is precisely the split-brain this rebuild exists to remove.
 */
export function visibleItemWhere(): Prisma.MenuItemWhereInput | undefined {
  if (!HIDE_DISHES_WITHOUT_OWN_PHOTO) return undefined
  return { imageUrl: { startsWith: OWN_PHOTO_PREFIX } }
}

/**
 * Categories that still have something in them.
 *
 * Without this, hiding every dessert leaves a "Desserts" heading with nothing under it — which
 * reads as a broken page rather than a shortened menu.
 */
export function visibleCategoryWhere(): Prisma.MenuCategoryWhereInput | undefined {
  const items = visibleItemWhere()
  return items ? { items: { some: items } } : undefined
}

/** True when a menu has been left with no categories at all and should not be listed. */
export function hasVisibleContent(menu: { categories: { items: unknown[] }[] }): boolean {
  return menu.categories.some((category) => category.items.length > 0)
}
