/**
 * Generates the three documents the restaurant owner actually has to act on:
 *
 *   QUESTIONS_FOR_CLIENT.md   things only they can decide
 *   COPY_CHANGES.md           every word we changed, so they can veto any of it
 *   ALLERGEN_TODO.md          the legal blocker, as a worksheet
 *
 * Generated rather than hand-written so they cannot drift from what the seed actually did.
 * Run with `npm run docs`.
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { loadSourceFile, transform, type ClientQuestion } from '../prisma/source-data'
import { ALL_ALLERGENS, ALLERGEN_LABELS } from '../src/lib/allergens'
import { formatMinutes, summariseWeek } from '../src/lib/hours'

const ROOT = process.cwd()
const GENERATED = `<!-- Generated by \`npm run docs\`. Edit prisma/source-data.ts, not this file. -->`

/**
 * Typos the site audit found and the scrape had already corrected before the JSON reached us.
 * Listed so COPY_CHANGES.md is a complete record of the difference between the old site's words
 * and the new site's words, not just the difference the seed happened to make.
 */
const CORRECTED_UPSTREAM = [
  { from: 'Handi Ghost', to: 'Handi Gosht', where: 'Food Menu › Main Course Lamb' },
  { from: 'flovoured', to: 'flavoured', where: 'Dish descriptions, several' },
  { from: 'succlent', to: 'succulent', where: 'Dish descriptions, several' },
  { from: 'fravy', to: 'gravy', where: 'Dish descriptions, several' },
  { from: 'Brocolli', to: 'Broccoli', where: 'Food Menu › Sharing Platters › Vegetarian Tandoor Platter' },
]

/** Site furniture rewritten wholesale rather than corrected word by word. */
const CHROME_REWRITES = [
  {
    where: 'Homepage hours heading',
    from: 'Opennig Hours',
    to: 'Opening hours',
    reason: 'Spelling.',
  },
  {
    where: 'Footer',
    from: 'Javatri 2026.All Rights Reserved',
    to: '© 2026 Javatri at The Bell and Bottle. All rights reserved.',
    reason: 'Missing space, missing symbol, and the trading name was truncated.',
  },
  {
    where: 'Brand name, TikTok link',
    from: 'Javitri',
    to: 'Javatri',
    reason:
      'The site spells the restaurant two different ways. Everything on the new site is "Javatri"; please confirm that is the spelling you want.',
  },
  {
    where: 'Homepage "View Specials" button',
    from: 'Linked to the homepage',
    to: 'Removed',
    reason: 'It went nowhere. A button that reloads the page you are on is worse than no button.',
  },
  {
    where: 'Banqueting "VIEW OUR MENU" button',
    from: 'Linked to the homepage',
    to: 'Links to /menu',
    reason: 'It went nowhere. It now goes to the menu.',
  },
  {
    where: 'Header "ORDER ONLINE", homepage "ONLINE ORDERING", "View our Menu"',
    from: 'Three buttons, three different broken ordering pages',
    to: 'All order buttons go to /order; "View our menu" goes to /menu',
    reason:
      'The single most expensive bug on the old site. There is now one ordering route and one menu route.',
  },
]

function severityRank(q: ClientQuestion): number {
  return { blocker: 0, important: 1, 'tidy-up': 2 }[q.severity]
}

function questionsDoc(questions: ClientQuestion[]): string {
  const sorted = [...questions].sort(
    (a, b) => severityRank(a) - severityRank(b) || a.area.localeCompare(b.area),
  )
  const blockers = sorted.filter((q) => q.severity === 'blocker')
  const important = sorted.filter((q) => q.severity === 'important')
  const tidy = sorted.filter((q) => q.severity === 'tidy-up')

  const section = (title: string, intro: string, items: ClientQuestion[]) => {
    if (items.length === 0) return ''
    const body = items
      .map(
        (q, i) => `### ${i + 1}. ${q.question}

${q.detail
  .split('\n')
  .map((line) => line)
  .join('\n')}

**What we did in the meantime.** ${q.weDidThisMeanwhile}
`,
      )
      .join('\n')
    return `## ${title}

${intro}

${body}`
  }

  return `# Questions for Javatri

${GENERATED}

Nothing in this list has been guessed. Where the old site was ambiguous, contradictory or empty, the
new site carries the scraped value forward unchanged, flags it, and waits for you.

There are **${blockers.length} blockers** (the site should not go live until these are answered),
**${important.length} important** items and **${tidy.length}** tidy-ups.

Most of the answers can be entered by your staff at \`/admin\` without a developer. Where that is
true, the answer says so.

---

${section(
  'Blockers',
  'These either cost you money every day they are wrong, or carry legal risk.',
  blockers,
)}
---

${section('Important', 'Worth answering before launch, but not fatal.', important)}
---

${section('Tidy-ups', 'Small things. Answer them when convenient.', tidy)}`
}

function copyDoc(result: ReturnType<typeof transform>): string {
  const rows = result.copyChanges
    .map(
      (c) =>
        `| ${c.where} | ${escapeCell(c.from)} | ${escapeCell(c.to)} | ${escapeCell(c.reason)} |`,
    )
    .join('\n')

  const upstream = CORRECTED_UPSTREAM.map(
    (c) => `| ${c.where} | ${c.from} | ${c.to} | Spelling |`,
  ).join('\n')

  const chrome = CHROME_REWRITES.map(
    (c) => `| ${c.where} | ${escapeCell(c.from)} | ${escapeCell(c.to)} | ${escapeCell(c.reason)} |`,
  ).join('\n')

  return `# Copy changes

${GENERATED}

Every word that differs between the old site and the new one. Veto any of it and it goes back —
these are your words, not ours.

## Dish names and descriptions

Corrections applied when the menu was loaded into the new database.

| Where | Was | Now | Why |
|---|---|---|---|
${rows}

## Corrected before the data reached us

The site audit found these on the live site and corrected them while scraping, so they arrived
already fixed. Listed here so this document is a complete record of the difference between the old
site's words and the new site's.

| Where | Was | Now | Why |
|---|---|---|---|
${upstream}

## Site furniture

Rewritten rather than corrected word by word.

| Where | Was | Now | Why |
|---|---|---|---|
${chrome}

## What we deliberately did not change

- **No prices were changed.** Every price on the new site is the price scraped from yours, including
  the ones that look wrong. See \`QUESTIONS_FOR_CLIENT.md\`.
- **No descriptions were written.** The Indian Street Food dishes have no descriptions on your site,
  so they have none here. Making them up would be putting words in your mouth.
- **No dietary tags were added.** Several dishes sit in vegetarian sections without a vegetarian tag.
  We flagged the contradiction rather than resolving it — see the Dietary questions.
- **No allergens were guessed.** See \`ALLERGEN_TODO.md\`.
`
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

function allergenDoc(result: ReturnType<typeof transform>): string {
  const byMenu = new Map<string, typeof result.allergenTodo>()
  for (const row of result.allergenTodo) {
    byMenu.set(row.menu, [...(byMenu.get(row.menu) ?? []), row])
  }

  const key = ALL_ALLERGENS.map((a, i) => `${i + 1}. **${ALLERGEN_LABELS[a]}**`).join('\n')

  const sections = [...byMenu.entries()]
    .map(([menu, rows]) => {
      const byCategory = new Map<string, typeof rows>()
      for (const row of rows) {
        byCategory.set(row.category, [...(byCategory.get(row.category) ?? []), row])
      }
      const body = [...byCategory.entries()]
        .map(([category, items]) => {
          const lines = items
            .map(
              (i) =>
                `| ${i.item} | £${(i.priceInPence / 100).toFixed(2)} | | ${
                  i.hints.length > 0 ? i.hints.join(' ') : ''
                } |`,
            )
            .join('\n')
          return `#### ${category}

| Dish | Price | Allergens present | Worth checking |
|---|---|---|---|
${lines}
`
        })
        .join('\n')
      return `### ${menu} — ${rows.length} dishes

${body}`
    })
    .join('\n---\n\n')

  return `# Allergen worksheet

${GENERATED}

**This is the one thing on the list that is a legal requirement rather than an improvement.**

There is no allergen information anywhere on the current Javatri site. Under assimilated Regulation
(EU) 1169/2011, enforced by the FSA and by Windsor and Maidenhead's environmental health team,
allergen information for the 14 regulated allergens has to be available for every dish you sell. For
online orders it has to be available twice: before the customer commits to the order, and again when
the food is handed over.

The new site has the whole system built — a field on every dish, a filter on the menu, the allergen
list on every dish card, and the standard notice at the top of the menu and again at checkout. What
it does not have is your data, because **guessing an allergen is not a design decision, it is a
gamble with somebody's airway.** Every dish below is currently marked *"allergen information not yet
confirmed — please call us"*, which is honest, and which is what a customer will see until this
worksheet is filled in.

## The 14

${key}

## How to fill this in

Two options, whichever suits the kitchen:

1. **In the admin area.** Go to \`/admin/menu\`, open a dish, tick the allergens, save. The dish
   immediately stops saying "not yet confirmed". This is the quickest route and needs no developer.
2. **On paper.** Print this file, write in the "Allergens present" column, hand it back, and it can
   be loaded in bulk.

The "worth checking" column is a *prompt*, not an answer. It is generated from words in the dish name
and description — "naan" suggests someone should check for gluten. It is not a claim about your
recipe. An empty prompt does not mean a dish is free of allergens; it means no obvious keyword
appeared. **Every dish needs a human decision, including the ones with a blank prompt.**

Note also that several sauces are shared across dishes. If your korma base contains cashew, that
affects every dish built on it, not just the ones with "korma" in the name.

---

## ${result.allergenTodo.length} dishes to confirm

${sections}`
}

function main() {
  const result = transform(loadSourceFile(ROOT))

  writeFileSync(path.join(ROOT, 'QUESTIONS_FOR_CLIENT.md'), questionsDoc(result.questions), 'utf8')
  writeFileSync(path.join(ROOT, 'COPY_CHANGES.md'), copyDoc(result), 'utf8')
  writeFileSync(path.join(ROOT, 'ALLERGEN_TODO.md'), allergenDoc(result), 'utf8')

  const hours = summariseWeek(
    result.branches[0].openingHours.map((h) => ({
      dayOfWeek: h.dayOfWeek,
      opensAt: h.opensAt,
      closesAt: h.closesAt,
    })),
  )

  console.log('Wrote QUESTIONS_FOR_CLIENT.md, COPY_CHANGES.md, ALLERGEN_TODO.md')
  console.log(
    `  ${result.questions.length} questions (${
      result.questions.filter((q) => q.severity === 'blocker').length
    } blockers), ${result.copyChanges.length} copy changes, ${result.allergenTodo.length} dishes needing allergens`,
  )
  console.log(`  Seeded hours: ${hours.map((h) => `${h.label} ${h.hours}`).join(' · ')}`)
  console.log(`  First service window opens at ${formatMinutes(result.branches[0].openingHours[0].opensAt)}`)
}

main()
